########################################################
# START CAMERA

POST http://localhost:8080/detector?businessKey=instance1
Content-Type: application/json
Accept: application/json

########################################################
# START PERSON DETECTOR

POST http://localhost:8080/surveillance?businessKey=instance1
Content-Type: application/json
Accept: application/json

######################################################## 
# GET INSTANCE IDS BY WORKFLOW

GET http://localhost:8080/detector