@startuml
state camera {
    state "idle" as b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle
    [*] --> b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle
    
    state "notifyPersonDetector" as b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_notifyPersonDetector
    state "notifyPersonDetector" as b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_notifyPersonDetector : entry / <color:#9B59B6>Raise{external_event_checkIfPersonsInImage}()</color>; 
    
    b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle --> b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle : **event_capture**\n/ <color:#1F618D>Invoke{camera.capture}([{video_number = 1}, {delay = 30}])</color>; 
    b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle --> b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_notifyPersonDetector : **event_checkIfPersonsInImage**
    b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_notifyPersonDetector --> b764a751_ff69_4f2f_9f8d_ce32f1c5b16f_idle
}
state personDetector {
    state "idle" as 15e5a12f_b604_40ce_8371_b69611820d9a_idle
    [*] --> 15e5a12f_b604_40ce_8371_b69611820d9a_idle
    
    state "decide" as 15e5a12f_b604_40ce_8371_b69611820d9a_decide
    
    state "foundPersons" as 15e5a12f_b604_40ce_8371_b69611820d9a_foundPersons
    state "foundPersons" as 15e5a12f_b604_40ce_8371_b69611820d9a_foundPersons : entry / <color:#9B59B6>Raise{external_event_personDetected}()</color>; 
    
    15e5a12f_b604_40ce_8371_b69611820d9a_idle --> 15e5a12f_b604_40ce_8371_b69611820d9a_idle : **external_event_checkIfPersonsInImage**\n/ <color:#27AE60>Assign{personDetection_image = $personDetection_input}()</color>; <color:#1F618D>Invoke{personDetection.detect}([{image = personDetection_image}])</color>; 
    15e5a12f_b604_40ce_8371_b69611820d9a_idle --> 15e5a12f_b604_40ce_8371_b69611820d9a_decide : **event_decideIfPersonsDetected**
    15e5a12f_b604_40ce_8371_b69611820d9a_decide --> 15e5a12f_b604_40ce_8371_b69611820d9a_foundPersons : \n[personDetection_detected_persons]
    15e5a12f_b604_40ce_8371_b69611820d9a_decide --> 15e5a12f_b604_40ce_8371_b69611820d9a_idle : \n[!personDetection_detected_persons]
    15e5a12f_b604_40ce_8371_b69611820d9a_foundPersons --> 15e5a12f_b604_40ce_8371_b69611820d9a_idle
}
state surveillanceSystem {
    state "idle" as fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle
    [*] --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle
    
    state "decide" as fccd3278_933f_4037_b2ee_a6d0d6f3473b_decide
    
    state "notifySecurity" as fccd3278_933f_4037_b2ee_a6d0d6f3473b_notifySecurity
    state "notifySecurity" as fccd3278_933f_4037_b2ee_a6d0d6f3473b_notifySecurity : entry / <color:#9B59B6>Raise{global_event_alarm}()</color>; 
    
    fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle : **external_event_personDetected**\n/ <color:#27AE60>Assign{faceDetection_image = $faceDetection_input}()</color>; <color:#1F618D>Invoke{faceDetection.detect}([{image = faceDetection_image}])</color>; 
    fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_decide : **event_decideIfPersonIsWhiteListed**
    fccd3278_933f_4037_b2ee_a6d0d6f3473b_decide --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_notifySecurity : \n[personDetection_detected_persons]
    fccd3278_933f_4037_b2ee_a6d0d6f3473b_decide --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle : \n[!personDetection_detected_persons]
    fccd3278_933f_4037_b2ee_a6d0d6f3473b_notifySecurity --> fccd3278_933f_4037_b2ee_a6d0d6f3473b_idle
}
@enduml