# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContextVariable.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43ontextVariable.proto\x12\x08\x65xchange\"?\n\x0f\x43ontextVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.exchange.Value\";\n\x10\x43ontextVariables\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x19.exchange.ContextVariable\"\x89\x01\n\x05Value\x12\x11\n\x07integer\x18\x01 \x01(\x05H\x00\x12\x0f\n\x05\x66loat\x18\x02 \x01(\x02H\x00\x12\x0e\n\x04long\x18\x03 \x01(\x03H\x00\x12\x10\n\x06\x64ouble\x18\x04 \x01(\x01H\x00\x12\x10\n\x06string\x18\x05 \x01(\tH\x00\x12\x0e\n\x04\x62ool\x18\x06 \x01(\x08H\x00\x12\x0f\n\x05\x62ytes\x18\x07 \x01(\x0cH\x00\x42\x07\n\x05valueBK\n0at.ac.uibk.dps.cirrina.execution.object.exchangeB\x15\x43ontextVariableProtosP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContextVariable_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0at.ac.uibk.dps.cirrina.execution.object.exchangeB\025ContextVariableProtosP\000'
  _globals['_CONTEXTVARIABLE']._serialized_start=35
  _globals['_CONTEXTVARIABLE']._serialized_end=98
  _globals['_CONTEXTVARIABLES']._serialized_start=100
  _globals['_CONTEXTVARIABLES']._serialized_end=159
  _globals['_VALUE']._serialized_start=162
  _globals['_VALUE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
