@startuml
state camera {
    state "idle" as 0e0e734a_1741_408c_a598_f574e1c25a76_idle
    [*] --> 0e0e734a_1741_408c_a598_f574e1c25a76_idle
    
    state "notifyPersonDetector" as 0e0e734a_1741_408c_a598_f574e1c25a76_notifyPersonDetector
    state "notifyPersonDetector" as 0e0e734a_1741_408c_a598_f574e1c25a76_notifyPersonDetector : entry / <color:#9B59B6>Raise{external_event_checkIfPersonsInImage}()</color>; 
    
    0e0e734a_1741_408c_a598_f574e1c25a76_idle --> 0e0e734a_1741_408c_a598_f574e1c25a76_idle : **event_capture**\n/ <color:#1F618D>Invoke{camera.capture}([{video_number = 1}, {delay = 30}])</color>; 
    0e0e734a_1741_408c_a598_f574e1c25a76_idle --> 0e0e734a_1741_408c_a598_f574e1c25a76_notifyPersonDetector : **event_checkIfPersonsInImage**
    0e0e734a_1741_408c_a598_f574e1c25a76_notifyPersonDetector --> 0e0e734a_1741_408c_a598_f574e1c25a76_idle
}
state personDetector {
    state "idle" as 88493cd6_cf20_4acf_baad_b117ac20500f_idle
    [*] --> 88493cd6_cf20_4acf_baad_b117ac20500f_idle
    
    state "decide" as 88493cd6_cf20_4acf_baad_b117ac20500f_decide
    
    state "foundPersons" as 88493cd6_cf20_4acf_baad_b117ac20500f_foundPersons
    state "foundPersons" as 88493cd6_cf20_4acf_baad_b117ac20500f_foundPersons : entry / <color:#9B59B6>Raise{external_event_personDetected}()</color>; 
    
    88493cd6_cf20_4acf_baad_b117ac20500f_idle --> 88493cd6_cf20_4acf_baad_b117ac20500f_idle : **external_event_checkIfPersonsInImage**\n/ <color:#27AE60>Assign{personDetection_image = $personDetection_input}()</color>; <color:#1F618D>Invoke{personDetection.detect}([{image = personDetection_image}])</color>; 
    88493cd6_cf20_4acf_baad_b117ac20500f_idle --> 88493cd6_cf20_4acf_baad_b117ac20500f_decide : **event_decideIfPersonsDetected**
    88493cd6_cf20_4acf_baad_b117ac20500f_decide --> 88493cd6_cf20_4acf_baad_b117ac20500f_foundPersons : \n[personDetection_detected_persons]
    88493cd6_cf20_4acf_baad_b117ac20500f_decide --> 88493cd6_cf20_4acf_baad_b117ac20500f_idle : \n[!personDetection_detected_persons]
    88493cd6_cf20_4acf_baad_b117ac20500f_foundPersons --> 88493cd6_cf20_4acf_baad_b117ac20500f_idle
}
state surveillanceSystem {
    state "idle" as 38d7feae_3311_4403_8fe0_869a4a999c84_idle
    [*] --> 38d7feae_3311_4403_8fe0_869a4a999c84_idle
    
    state "decide" as 38d7feae_3311_4403_8fe0_869a4a999c84_decide
    
    state "notifySecurity" as 38d7feae_3311_4403_8fe0_869a4a999c84_notifySecurity
    state "notifySecurity" as 38d7feae_3311_4403_8fe0_869a4a999c84_notifySecurity : entry / <color:#9B59B6>Raise{global_event_alarm}()</color>; 
    
    38d7feae_3311_4403_8fe0_869a4a999c84_idle --> 38d7feae_3311_4403_8fe0_869a4a999c84_idle : **external_event_personDetected**\n/ <color:#27AE60>Assign{faceDetection_image = $faceDetection_input}()</color>; <color:#1F618D>Invoke{faceDetection.detect}([{image = faceDetection_image}])</color>; 
    38d7feae_3311_4403_8fe0_869a4a999c84_idle --> 38d7feae_3311_4403_8fe0_869a4a999c84_decide : **event_decideIfPersonIsWhiteListed**
    38d7feae_3311_4403_8fe0_869a4a999c84_decide --> 38d7feae_3311_4403_8fe0_869a4a999c84_notifySecurity : \n[personDetection_detected_persons]
    38d7feae_3311_4403_8fe0_869a4a999c84_decide --> 38d7feae_3311_4403_8fe0_869a4a999c84_idle : \n[!personDetection_detected_persons]
    38d7feae_3311_4403_8fe0_869a4a999c84_notifySecurity --> 38d7feae_3311_4403_8fe0_869a4a999c84_idle
}
@enduml